apiVersion: v1
description: A Helm chart for a General Purpose Chassis Monitoring Exporter using the redfish API
name: fishymetrics
version: 0.6.0
appVersion: 0.8.0
maintainers:
- name: Derrick DaCosta
  email: derrick_dacosta@cable.comcast.com
